### PR TITLE
Removed Duplicate: darkgrey [169,169,169]

### PR DESCRIPTION
**Pull request by Erick559**

### CODE REVIEW

**Comment by AnshSinghSonkhia** [comment]
Great Work @Erick559

**Review by AnshSinghSonkhia — APPROVED** [review]
You can also remove, "darkgrey" from the README.md file.

**Comment by AnshSinghSonkhia** [comment]
Hey @Erick559,
You can Star the repo for more PRs :)

**Comment by Erick559** [comment]
No worries

**Pull request merged**
